export const data=[
   
   {
      "brand": "ACURA",
      "model": "MDX",
      "volume": "3.5 л",
      "power": "290 л.с.",
      "box": "Автомат",
      "engines_type": "бензиновый",
      "fuel": "АИ-95",
      "drive_unit": "полный",
      "consumption": "11.2 л",
      "brand country": "Япония",
      "car_class": "E",
      "number_of_seats": "7",
      "steering_wheel_position": "Левый",
      "number_of_doors": "4",
      "imgSrc": "../img/font-img/acura_mdx.png"
   },
   {
      "brand": "DAIHATSA",
      "model": "Tanto",
      "volume": "0.7 л",
      "power": "52 л.с.",
      "box": "Вариатор ",
      "engines_type": "бензиновый",
      "fuel": "АИ-92",
      "drive_unit": "передний",
      "consumption": "3.6 л",
      "brand country": "Япония",
      "car_class": "A",
      "number_of_seats": "5",
      "steering_wheel_position": "Правый",
      "number_of_doors": "4",
      "imgSrc": "../img/font-img/Daihatsu-Tanto-Premium-Version-1.png"
   },
   {
      "brand": "DATSUN",
      "model": "mi-DO",
      "volume": "1.6 л",
      "power": "87 л.с.",
      "box": "Механика",
      "engines_type": "бензиновый",
      "fuel": "АИ-95",
      "drive_unit": "передний",
      "consumption": "7.0 л",
      "brand country": "Япония",
      "car_class": "B",
      "number_of_seats": "5",
      "steering_wheel_position": "Левый",
      "number_of_doors": "5",
      "imgSrc": "../img/font-img/datsun-mi-do-.png"
   },
   {
      "brand": "HINO",
      "model": "500",
      "volume": "7.7 л",
      "power": "260 л.с",
      "box": "МКПП",
      "engines_type": "Дизель",
      "fuel": "Дизель",
      "drive_unit": "Задний",
      "consumption": "",
      "brand country": "Япония",
      "car_class": "21-23 л",
      "number_of_seats": "2",
      "steering_wheel_position": "Правый",
      "number_of_doors": "2",
      "imgSrc": "../img/font-img/hino.png"
   },
   {
      "brand": "HONDA",
      "model": "Accord-11",
      "volume": "2.0л",
      "power": "207 л.с.",
      "box": "Вариатор",
      "engines_type": "гибридный",
      "fuel": "АИ-95",
      "drive_unit": "передний",
      "consumption": "5.3 л",
      "brand_country": "Япония",
      "car_class": "D",
      "number_of_seats": "5",
      "steering_wheel_position": "Левый",
      "number_of_doors": "4",
      "imgSrc": "../img/font-img/honda_accord.png"
   },
   {
      "brand": "INFINITIY",
      "model": "Infiniti QX80",
      "volume": "5.6 л",
      "power": "405 л.с.",
      "box": "Автомат",
      "engines_type": "бензиновый",
      "fuel": "АИ-95",
      "drive_unit": "полный",
      "consumption": "14.5 л",
      "brand country": "Япония",
      "car_class": "J",
      "number_of_seats": "7,8",
      "steering_wheel_position": "Левый",
      "number_of_doors": "5",
      "imgSrc": "../img/font-img/Infiniti-QX80.png"
   },
   {
      "brand": "ISUZU",
      "model": "D-Max II",
      "volume": "3.0 л",
      "power": "177 л.с",
      "box": "Автомат",
      "engines_type": "дизельный",
      "fuel": "ДТ",
      "drive_unit": "полный",
      "consumption": "8.0 л",
      "brand country": "Япония",
      "car_class": "J",
      "number_of_seats": "7,8",
      "steering_wheel_position": "Левый",
      "number_of_doors": "5",
      "imgSrc": "../img/font-img/isuzu-d-max.png"
   },
   {
      "brand": "LEXUS",
      "model": "Lexus-LX-570",
      "volume": "5.7 л",
      "power": "367 л.с.",
      "box": "Автомат",
      "engines_type": "бензиновый",
      "fuel": "АИ-92",
      "drive_unit": "полный",
      "consumption": "14.8 л",
      "brand country": "Япония",
      "car_class": "J",
      "number_of_seats": "8",
      "steering_wheel_position": "Левый/Правый",
      "number_of_doors": "5",
      "imgSrc": "../img/font-img/Lexus-LX-570.png"
   },
   {
      "brand": "MAZDA",
      "model": "mazda-6",
      "volume": "2 л",
      "power": "231 л.с",
      "box": "Автомат",
      "engines_type": "бензиновый",
      "fuel": "АИ-92",
      "drive_unit": "передний",
      "consumption": "6,5-7,7",
      "brand country": "Япония",
      "car_class": "J",
      "number_of_seats": "5",
      "steering_wheel_position": "Левый",
      "number_of_doors": "4",
      "imgSrc": "../img/font-img/mazda-6-2023.png"
   },
   {
      "brand": "MITSUBISHI",
      "model": "Lancer",
      "volume": "1.8",
      "power": "140",
      "box": "Вариатор",
      "engines_type": "Бензиновый",
      "fuel": "АИ-95",
      "drive_unit": "Передняя",
      "consumption": "10.9 л",
      "brand country": "Япония",
      "car_class": "J",
      "number_of_seats": "5",
      "steering_wheel_position": "Левый",
      "number_of_doors": "4",
      "imgSrc": "../img/font-img/mitsubishi- lancer.png"
   },
   {
      "brand": "MITSUKA",
      "model": "Orochi",
      "volume": "3.3 л",
      "power": "223 л.с.",
      "box": "Автомат",
      "engines_type": "бензиновый",
      "fuel": "АИ-98",
      "drive_unit": "передний",
      "consumption": "11.6 л",
      "brand country": "Япония",
      "car_class": "S",
      "number_of_seats": "2",
      "steering_wheel_position": "Левый/Правый",
      "number_of_doors": "2",
      "imgSrc": "../img/font-img/mitsuoka-orochi.png"
   },
   {
      "brand": "NISSAN",
      "model": "Altima",
      "volume": "2.5 л",
      "power": "182 л.с",
      "box": "Вариатор",
      "engines_type": "бензиновый",
      "fuel": "АИ-95",
      "drive_unit": "полный",
      "consumption": "7.8 л",
      "brand country": "Япония",
      "car_class": "D",
      "number_of_seats": "5",
      "steering_wheel_position": "Левый",
      "number_of_doors": "4",
      "imgSrc": "../img/font-img/Nissan_Altima_2023.png"
   },
   {
      "brand": "SCION",
      "model": "tC II Рестайлинг",
      "volume": "2.5 л",
      "power": "180 л.с",
      "box": "Механика",
      "engines_type": "бензиновый",
      "fuel": "АИ-92",
      "drive_unit": "передний",
      "consumption": "9.0 л",
      "brand country": "США",
      "car_class": "S",
      "number_of_seats": "5",
      "steering_wheel_position": "Левый",
      "number_of_doors": "2",
      "imgSrc": "../img/font-img/SCION tc.png"
   },
   {
      "brand": "SUBARU",
      "model": "Impreza VI",
      "volume": "2.0 л",
      "power": "145 л.с.",
      "box": "Вариатор ",
      "engines_type": "гибридный",
      "fuel": "АИ-95",
      "drive_unit": "передний",
      "consumption": "6.0 л",
      "brand country": "Япония",
      "car_class": "C",
      "number_of_seats": "5",
      "steering_wheel_position": "Левый/Правый",
      "number_of_doors": "5",
      "imgSrc": "../img/font-img/SUBARU impreza.png"
   },
   {
      "brand": "TOYOTA",
      "model": " Corolla XII (E210)",
      "volume": "1.6 л",
      "power": "122 л.с",
      "box": "Вариатор",
      "engines_type": "бензиновый",
      "fuel": "АИ-95",
      "drive_unit": "передний",
      "consumption": "6.3 л",
      "brand country": "Япония",
      "car_class": "C",
      "number_of_seats": "5",
      "steering_wheel_position": "Левый/Правый",
      "number_of_doors": "4",
      "imgSrc": "../img/font-img/toyota-gr-corolla-2023.png"
   }
]